package com.nelu.alquran

object temp {
    val html = """
        <table class="transList sortable">
		<thead>
			<tr class="tr-head">
				<th class="td-lang">Language</th>
				<th class="td-name">Name</th>
				<th class="td-translator">Translator</th>
				<th class="td-action sorttable_nosort">Action</th>
			</tr>
		</thead>
		<tbody>
		<tr><td><i class="al flag"></i>Albanian</td><td>Efendi Nahi</td><td>Hasan Efendi Nahi</td><td><a href="/trans/sq.nahi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/sq.nahi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/sq.nahi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="al flag"></i>Albanian</td><td>Feti Mehdiu</td><td>Feti Mehdiu</td><td><a href="/trans/sq.mehdiu" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/sq.mehdiu/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/sq.mehdiu" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="al flag"></i>Albanian</td><td>Sherif Ahmeti</td><td>Sherif Ahmeti</td><td><a href="/trans/sq.ahmeti" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/sq.ahmeti/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/sq.ahmeti" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="dz flag"></i>Amazigh</td><td>At Mensur</td><td>Ramdane At Mansour&nbsp;<a href="http://www.africultures.com/php/index.php?nav=personne&amp;no=6383" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ber.mensur" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ber.mensur/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ber.mensur" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="sa flag"></i>Arabic</td><td>تفسير الجلالين</td><td>Jalal ad-Din al-Mahalli and Jalal ad-Din as-Suyuti&nbsp;<a href="http://en.wikipedia.org/wiki/Tafsir_al-Jalalayn" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ar.jalalayn" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ar.jalalayn/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ar.jalalayn" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="sa flag"></i>Arabic</td><td>تفسير المیسر</td><td>King Fahad Quran Complex&nbsp;<a href="http://www.qurancomplex.org/quran/Tafseer/IntroTafseer.asp?l=arb&amp;Tafseer=moyasar" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ar.muyassar" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ar.muyassar/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ar.muyassar" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="et flag"></i>Amharic </td><td>ሳዲቅ &amp; ሳኒ ሐቢብ</td><td>Muhammed Sadiq and Muhammed Sani Habib&nbsp;<a href="http://en.wikipedia.org/wiki/Shekh_Muhammad_Tānī" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/am.sadiq" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/am.sadiq/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/am.sadiq" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="az flag"></i>Azerbaijani</td><td>Məmmədəliyev &amp; Bünyadov</td><td>Vasim Mammadaliyev and Ziya Bunyadov&nbsp;<a href="http://az.wikipedia.org/wiki/Vasim_Məmmədəliyev" title="Biography" class="bio"><sup>*</sup></a>&nbsp;<a href="http://en.wikipedia.org/wiki/Ziya_Bunyadov" title="Biography" class="bio"><sup>†</sup></a></td><td><a href="/trans/az.mammadaliyev" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/az.mammadaliyev/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/az.mammadaliyev" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="az flag"></i>Azerbaijani</td><td>Musayev</td><td>Alikhan Musayev</td><td><a href="/trans/az.musayev" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/az.musayev/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/az.musayev" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="bd flag"></i>Bengali</td><td>জহুরুল হক</td><td>Zohurul Hoque&nbsp;<a href="http://en.wikipedia.org/wiki/Zohurul_Hoque" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/bn.hoque" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/bn.hoque/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/bn.hoque" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="bd flag"></i>Bengali</td><td>মুহিউদ্দীন খান</td><td>Muhiuddin Khan</td><td><a href="/trans/bn.bengali" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/bn.bengali/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/bn.bengali" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ba flag"></i>Bosnian</td><td>Korkut</td><td>Besim Korkut&nbsp;<a href="http://bosnjaci.net/dobri_bosnjani.php?id=93" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/bs.korkut" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/bs.korkut/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/bs.korkut" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ba flag"></i>Bosnian</td><td>Mlivo</td><td>Mustafa Mlivo</td><td><a href="/trans/bs.mlivo" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/bs.mlivo/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/bs.mlivo" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="bg flag"></i>Bulgarian</td><td>Теофанов</td><td>Tzvetan Theophanov</td><td><a href="/trans/bg.theophanov" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/bg.theophanov/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/bg.theophanov" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="cn flag"></i>Chinese</td><td>Ma Jian</td><td>Ma Jian</td><td><a href="/trans/zh.jian" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/zh.jian/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/zh.jian" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tw flag"></i>Chinese</td><td>Ma Jian (Traditional)</td><td>Ma Jian</td><td><a href="/trans/zh.majian" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/zh.majian/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/zh.majian" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="cz flag"></i>Czech</td><td>Hrbek</td><td>Preklad I. Hrbek</td><td><a href="/trans/cs.hrbek" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/cs.hrbek/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/cs.hrbek" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="cz flag"></i>Czech</td><td>Nykl</td><td>A. R. Nykl</td><td><a href="/trans/cs.nykl" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/cs.nykl/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/cs.nykl" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="mv flag"></i>Divehi</td><td>ދިވެހި</td><td>Office of the President of Maldives</td><td><a href="/trans/dv.divehi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/dv.divehi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/dv.divehi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="nl flag"></i>Dutch</td><td>Keyzer</td><td>Salomo Keyzer </td><td><a href="/trans/nl.keyzer" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/nl.keyzer/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/nl.keyzer" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="nl flag"></i>Dutch</td><td>Leemhuis</td><td>Fred Leemhuis</td><td><a href="/trans/nl.leemhuis" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/nl.leemhuis/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/nl.leemhuis" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="nl flag"></i>Dutch</td><td>Siregar</td><td>Sofian S. Siregar</td><td><a href="/trans/nl.siregar" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/nl.siregar/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/nl.siregar" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Ahmed Ali</td><td>Ahmed Ali&nbsp;<a href="http://en.wikipedia.org/wiki/Ahmed_Ali" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.ahmedali" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.ahmedali/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.ahmedali" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Ahmed Raza Khan</td><td>Ahmed Raza Khan&nbsp;<a href="http://en.wikipedia.org/wiki/Ahmed_Rida_Khan" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.ahmedraza" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.ahmedraza/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.ahmedraza" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Arberry</td><td>A. J. Arberry&nbsp;<a href="http://en.wikipedia.org/wiki/A._J._Arberry" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.arberry" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.arberry/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.arberry" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Daryabadi</td><td>Abdul Majid Daryabadi&nbsp;<a href="http://en.wikipedia.org/wiki/Abdul_Majid_Daryabadi" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.daryabadi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.daryabadi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.daryabadi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Hilali &amp; Khan</td><td>Muhammad Taqi-ud-Din al-Hilali and Muhammad Muhsin Khan&nbsp;<a href="http://en.wikipedia.org/wiki/Hilali-Khan" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.hilali" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.hilali/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.hilali" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Itani</td><td>Talal Itani</td><td><a href="/trans/en.itani" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.itani/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.itani" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Maududi</td><td>Abul Ala Maududi&nbsp;<a href="http://en.wikipedia.org/wiki/Maududi" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.maududi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.maududi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.maududi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Mubarakpuri</td><td>Safi-ur-Rahman al-Mubarakpuri&nbsp;<a href="http://en.wikipedia.org/wiki/Safiur_Rahman_Mubarakpuri" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.mubarakpuri" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.mubarakpuri/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.mubarakpuri" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Pickthall</td><td>Mohammed Marmaduke William Pickthall&nbsp;<a href="http://en.wikipedia.org/wiki/Marmaduke_Pickthall" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.pickthall" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.pickthall/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.pickthall" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Qarai</td><td>Ali Quli Qarai</td><td><a href="/trans/en.qarai" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.qarai/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.qarai" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Qaribullah &amp; Darwish</td><td>Hasan al-Fatih Qaribullah and Ahmad Darwish</td><td><a href="/trans/en.qaribullah" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.qaribullah/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.qaribullah" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Saheeh International</td><td>Saheeh International&nbsp;<a href="http://www.saheehinternational.com" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.sahih" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.sahih/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.sahih" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Sarwar</td><td>Muhammad Sarwar&nbsp;<a href="http://en.wikipedia.org/wiki/Muhammad_Shaykh_Sarwar" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.sarwar" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.sarwar/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.sarwar" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Shakir</td><td>Mohammad Habib Shakir&nbsp;<a href="http://en.wikipedia.org/wiki/M._H._Shakir" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.shakir" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.shakir/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.shakir" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Transliteration</td><td>English Transliteration</td><td><a href="/trans/en.transliteration" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.transliteration/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.transliteration" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Wahiduddin Khan</td><td>Wahiduddin Khan&nbsp;<a href="http://en.wikipedia.org/wiki/Wahiduddin_Khan" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.wahiduddin" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.wahiduddin/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.wahiduddin" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="us flag"></i>English</td><td>Yusuf Ali</td><td>Abdullah Yusuf Ali&nbsp;<a href="http://en.wikipedia.org/wiki/Abdullah_Yusuf_Ali" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/en.yusufali" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/en.yusufali/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/en.yusufali" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="fr flag"></i>French</td><td>Hamidullah</td><td>Muhammad Hamidullah&nbsp;<a href="http://en.wikipedia.org/wiki/Muhammad_Hamidullah" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fr.hamidullah" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fr.hamidullah/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fr.hamidullah" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="de flag"></i>German</td><td>Abu Rida</td><td>Abu Rida Muhammad ibn Ahmad ibn Rassoul</td><td><a href="/trans/de.aburida" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/de.aburida/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/de.aburida" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="de flag"></i>German</td><td>Bubenheim &amp; Elyas</td><td>A. S. F. Bubenheim and N. Elyas&nbsp;<a href="http://de.wikipedia.org/wiki/Nadeem_Elyas" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/de.bubenheim" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/de.bubenheim/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/de.bubenheim" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="de flag"></i>German</td><td>Khoury</td><td>Adel Theodor Khoury&nbsp;<a href="http://de.wikipedia.org/wiki/Amir_Zaidan" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/de.khoury" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/de.khoury/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/de.khoury" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="de flag"></i>German</td><td>Zaidan</td><td>Amir Zaidan</td><td><a href="/trans/de.zaidan" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/de.zaidan/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/de.zaidan" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ng flag"></i>Hausa</td><td>Gumi</td><td>Abubakar Mahmoud Gumi</td><td><a href="/trans/ha.gumi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ha.gumi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ha.gumi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="in flag"></i>Hindi</td><td>फ़ारूक़ ख़ान &amp; अहमद</td><td>Muhammad Farooq Khan and Muhammad Ahmed  </td><td><a href="/trans/hi.farooq" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/hi.farooq/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/hi.farooq" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="in flag"></i>Hindi</td><td>फ़ारूक़ ख़ान &amp; नदवी</td><td>Suhel Farooq Khan and Saifur Rahman Nadwi</td><td><a href="/trans/hi.hindi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/hi.hindi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/hi.hindi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="id flag"></i>Indonesian</td><td>Bahasa Indonesia</td><td>Indonesian Ministry of Religious Affairs</td><td><a href="/trans/id.indonesian" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/id.indonesian/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/id.indonesian" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="id flag"></i>Indonesian</td><td>Quraish Shihab</td><td>Muhammad Quraish Shihab et al.&nbsp;<a href="http://id.wikipedia.org/wiki/Muhammad_Quraish_Shihab" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/id.muntakhab" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/id.muntakhab/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/id.muntakhab" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="id flag"></i>Indonesian</td><td>Tafsir Jalalayn</td><td>Jalal ad-Din al-Mahalli and Jalal ad-Din as-Suyuti&nbsp;<a href="http://en.wikipedia.org/wiki/Tafsir_al-Jalalayn" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/id.jalalayn" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/id.jalalayn/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/id.jalalayn" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="it flag"></i>Italian</td><td>Piccardo</td><td>Hamza Roberto Piccardo&nbsp;<a href="http://en.wikipedia.org/wiki/Hamza_Roberto_Piccardo" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/it.piccardo" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/it.piccardo/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/it.piccardo" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="jp flag"></i>Japanese</td><td>Japanese</td><td>Unknown</td><td><a href="/trans/ja.japanese" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ja.japanese/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ja.japanese" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="kr flag"></i>Korean</td><td>Korean</td><td>Unknown</td><td><a href="/trans/ko.korean" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ko.korean/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ko.korean" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="iq flag"></i>Kurdish</td><td>ته&zwnj;فسیری ئاسان</td><td>Burhan Muhammad-Amin</td><td><a href="/trans/ku.asan" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ku.asan/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ku.asan" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="my flag"></i>Malay</td><td>Basmeih</td><td>Abdullah Muhammad Basmeih</td><td><a href="/trans/ms.basmeih" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ms.basmeih/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ms.basmeih" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="in flag"></i>Malayalam</td><td>അബ്ദുല്&zwj; ഹമീദ് &amp; പറപ്പൂര്&zwj;</td><td>Cheriyamundam Abdul Hameed and Kunhi Mohammed Parappoor</td><td><a href="/trans/ml.abdulhameed" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ml.abdulhameed/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ml.abdulhameed" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="in flag"></i>Malayalam</td><td>കാരകുന്ന് &amp; എളയാവൂര്</td><td>Muhammad Karakunnu and Vanidas Elayavoor&nbsp;<a href="http://en.wikipedia.org/wiki/Sheikh_Muhammad_Karakunnu" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ml.karakunnu" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ml.karakunnu/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ml.karakunnu" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="no flag"></i>Norwegian</td><td>Einar Berg</td><td>Einar Berg</td><td><a href="/trans/no.berg" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/no.berg/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/no.berg" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="af flag"></i>Pashto</td><td>عبدالولي</td><td>Abdulwali Khan</td><td><a href="/trans/ps.abdulwali" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ps.abdulwali/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ps.abdulwali" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>انصاریان</td><td>Hussain Ansarian&nbsp;<a href="http://fa.wikipedia.org/wiki/حسین_انصاریان" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.ansarian" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.ansarian/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.ansarian" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>آیتی</td><td>AbdolMohammad Ayati&nbsp;<a href="http://fa.wikipedia.org/wiki/عبدالمحمد_آیتی" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.ayati" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.ayati/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.ayati" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>بهرام&zwnj;پور</td><td>Abolfazl Bahrampour&nbsp;<a href="http://fa.wikipedia.org/wiki/ابوالفضل_بهرام&zwnj;پور" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.bahrampour" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.bahrampour/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.bahrampour" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>قرائتی</td><td>Mohsen Gharaati&nbsp;<a href="http://fa.wikipedia.org/wiki/محسن_قرائتی" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.gharaati" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.gharaati/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.gharaati" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>الهی قمشه&zwnj;ای</td><td>Mahdi Elahi Ghomshei&nbsp;<a href="http://fa.wikipedia.org/wiki/مهدی_الهی_قمشه&zwnj;ای" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.ghomshei" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.ghomshei/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.ghomshei" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>خرمدل</td><td>Mostafa Khorramdel&nbsp;<a href="http://rasekhoon.net/mashahir/Show-904328.aspx" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.khorramdel" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.khorramdel/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.khorramdel" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>خرمشاهی</td><td>Baha'oddin Khorramshahi&nbsp;<a href="http://fa.wikipedia.org/wiki/بهاءالدین_خرمشاهی" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.khorramshahi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.khorramshahi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.khorramshahi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>صادقی تهرانی</td><td>Mohammad Sadeqi Tehrani&nbsp;<a href="http://fa.wikipedia.org/wiki/محمد_صادقی_تهرانی" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.sadeqi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.sadeqi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.sadeqi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>صفوی</td><td>Sayyed Mohammad Reza Safavi&nbsp;<a href="http://wikinoor.ir/صفوی،_سید_محمدرضا" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.safavi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.safavi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.safavi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>فولادوند</td><td>Mohammad Mahdi Fooladvand&nbsp;<a href="http://fa.wikipedia.org/wiki/محمدمهدی_فولادوند" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.fooladvand" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.fooladvand/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.fooladvand" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>مجتبوی</td><td>Sayyed Jalaloddin Mojtabavi&nbsp;<a href="http://rasekhoon.net/mashahir/Show-118481.aspx" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.mojtabavi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.mojtabavi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.mojtabavi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>معزی</td><td>Mohammad Kazem Moezzi</td><td><a href="/trans/fa.moezzi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.moezzi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.moezzi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ir flag"></i>Persian</td><td>مکارم شیرازی</td><td>Naser Makarem Shirazi&nbsp;<a href="http://en.wikipedia.org/wiki/Naser_Makarem_Shirazi" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/fa.makarem" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/fa.makarem/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/fa.makarem" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="pl flag"></i>Polish</td><td>Bielawskiego</td><td>Józefa Bielawskiego</td><td><a href="/trans/pl.bielawskiego" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/pl.bielawskiego/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/pl.bielawskiego" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="pt flag"></i>Portuguese</td><td>El-Hayek</td><td>Samir El-Hayek </td><td><a href="/trans/pt.elhayek" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/pt.elhayek/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/pt.elhayek" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ro flag"></i>Romanian</td><td>Grigore</td><td>George Grigore</td><td><a href="/trans/ro.grigore" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ro.grigore/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ro.grigore" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ru flag"></i>Russian</td><td>Абу Адель</td><td>Abu Adel</td><td><a href="/trans/ru.abuadel" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ru.abuadel/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ru.abuadel" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ru flag"></i>Russian</td><td>Аль-Мунтахаб</td><td>Ministry of Awqaf, Egypt</td><td><a href="/trans/ru.muntahab" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ru.muntahab/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ru.muntahab" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ru flag"></i>Russian</td><td>Калям Шариф</td><td>Muslim Religious Board of the Republiс of Tatarstan&nbsp;<a href="http://ru.wikipedia.org/wiki/Духовное_управление_мусульман_Республики_Татарстан" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ru.kalam" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ru.kalam/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ru.kalam" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ru flag"></i>Russian</td><td>Крачковский</td><td>Ignaty Yulianovich Krachkovsky&nbsp;<a href="http://ru.wikipedia.org/wiki/Крачковский,_Игнатий_Юлианович" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ru.krachkovsky" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ru.krachkovsky/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ru.krachkovsky" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ru flag"></i>Russian</td><td>Кулиев</td><td>Elmir Kuliev</td><td><a href="/trans/ru.kuliev" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ru.kuliev/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ru.kuliev" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ru flag"></i>Russian</td><td>Кулиев + ас-Саади</td><td>Elmir Kuliev (with Abd ar-Rahman as-Saadi's commentaries)</td><td><a href="/trans/ru.kuliev-alsaadi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ru.kuliev-alsaadi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ru.kuliev-alsaadi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ru flag"></i>Russian</td><td>Османов</td><td>Magomed-Nuri Osmanovich Osmanov</td><td><a href="/trans/ru.osmanov" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ru.osmanov/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ru.osmanov" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ru flag"></i>Russian</td><td>Порохова</td><td>V. Porokhova</td><td><a href="/trans/ru.porokhova" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ru.porokhova/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ru.porokhova" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ru flag"></i>Russian</td><td>Саблуков</td><td>Gordy Semyonovich Sablukov</td><td><a href="/trans/ru.sablukov" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ru.sablukov/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ru.sablukov" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="pk flag"></i>Sindhi</td><td>امروٽي</td><td>Taj Mehmood Amroti</td><td><a href="/trans/sd.amroti" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/sd.amroti/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/sd.amroti" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="so flag"></i>Somali</td><td>Abduh</td><td>Mahmud Muhammad Abduh</td><td><a href="/trans/so.abduh" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/so.abduh/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/so.abduh" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="es flag"></i>Spanish</td><td>Bornez</td><td>Raúl González Bórnez&nbsp;<a href="http://www.scribd.com/doc/72248854/Coran-en-castellano-Raul-Gonzalez-Bornez-DM" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/es.bornez" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/es.bornez/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/es.bornez" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="es flag"></i>Spanish</td><td>Cortes</td><td>Julio Cortes </td><td><a href="/trans/es.cortes" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/es.cortes/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/es.cortes" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="es flag"></i>Spanish</td><td>Garcia</td><td>Muhammad Isa García&nbsp;<a href="http://themuslim500.com/profile/prof-muhammad-isa-garcia" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/es.garcia" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/es.garcia/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/es.garcia" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ke flag"></i>Swahili</td><td>Al-Barwani</td><td>Ali Muhsin Al-Barwani</td><td><a href="/trans/sw.barwani" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/sw.barwani/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/sw.barwani" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="se flag"></i>Swedish</td><td>Bernström</td><td>Knut Bernström</td><td><a href="/trans/sv.bernstrom" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/sv.bernstrom/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/sv.bernstrom" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tj flag"></i>Tajik</td><td>Оятӣ</td><td>AbdolMohammad Ayati</td><td><a href="/trans/tg.ayati" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tg.ayati/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tg.ayati" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="in flag"></i>Tamil</td><td>ஜான் டிரஸ்ட்</td><td>Jan Turst Foundation</td><td><a href="/trans/ta.tamil" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ta.tamil/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ta.tamil" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="ru flag"></i>Tatar</td><td>Yakub Ibn Nugman</td><td>Yakub Ibn Nugman</td><td><a href="/trans/tt.nugman" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tt.nugman/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tt.nugman" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="th flag"></i>Thai</td><td>ภาษาไทย</td><td>King Fahad Quran Complex</td><td><a href="/trans/th.thai" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/th.thai/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/th.thai" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tr flag"></i>Turkish</td><td>Abdulbakî Gölpınarlı</td><td>Abdulbaki Golpinarli</td><td><a href="/trans/tr.golpinarli" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tr.golpinarli/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tr.golpinarli" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tr flag"></i>Turkish</td><td>Alİ Bulaç</td><td>Alİ Bulaç</td><td><a href="/trans/tr.bulac" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tr.bulac/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tr.bulac" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tr flag"></i>Turkish</td><td>Çeviriyazı</td><td>Muhammet Abay</td><td><a href="/trans/tr.transliteration" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tr.transliteration/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tr.transliteration" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tr flag"></i>Turkish</td><td>Diyanet İşleri</td><td>Diyanet Isleri</td><td><a href="/trans/tr.diyanet" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tr.diyanet/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tr.diyanet" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tr flag"></i>Turkish</td><td>Diyanet Vakfı</td><td>Diyanet Vakfi</td><td><a href="/trans/tr.vakfi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tr.vakfi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tr.vakfi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tr flag"></i>Turkish</td><td>Edip Yüksel</td><td>Edip Yüksel</td><td><a href="/trans/tr.yuksel" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tr.yuksel/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tr.yuksel" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tr flag"></i>Turkish</td><td>Elmalılı Hamdi Yazır</td><td>Elmalili Hamdi Yazir</td><td><a href="/trans/tr.yazir" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tr.yazir/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tr.yazir" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tr flag"></i>Turkish</td><td>Öztürk</td><td>Yasar Nuri Ozturk&nbsp;<a href="http://en.wikipedia.org/wiki/Yasar_Nuri_Ozturk" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/tr.ozturk" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tr.ozturk/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tr.ozturk" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tr flag"></i>Turkish</td><td>Suat Yıldırım</td><td>Suat Yildirim</td><td><a href="/trans/tr.yildirim" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tr.yildirim/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tr.yildirim" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="tr flag"></i>Turkish</td><td>Süleyman Ateş</td><td>Suleyman Ates</td><td><a href="/trans/tr.ates" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/tr.ates/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/tr.ates" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="pk flag"></i>Urdu</td><td>ابوالاعلی مودودی</td><td>Abul A'ala Maududi&nbsp;<a href="http://en.wikipedia.org/wiki/Maududi" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ur.maududi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ur.maududi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ur.maududi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="pk flag"></i>Urdu</td><td>احمد رضا خان</td><td>Ahmed Raza Khan&nbsp;<a href="http://en.wikipedia.org/wiki/Ahmed_Rida_Khan" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ur.kanzuliman" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ur.kanzuliman/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ur.kanzuliman" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="pk flag"></i>Urdu</td><td>احمد علی</td><td>Ahmed Ali&nbsp;<a href="http://en.wikipedia.org/wiki/Ahmed_Ali" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ur.ahmedali" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ur.ahmedali/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ur.ahmedali" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="pk flag"></i>Urdu</td><td>جالندہری</td><td>Fateh Muhammad Jalandhry</td><td><a href="/trans/ur.jalandhry" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ur.jalandhry/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ur.jalandhry" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="pk flag"></i>Urdu</td><td>طاہر القادری</td><td>Tahir ul Qadri&nbsp;<a href="http://en.wikipedia.org/wiki/Muhammad_Tahir-ul-Qadri" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ur.qadri" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ur.qadri/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ur.qadri" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="pk flag"></i>Urdu</td><td>علامہ جوادی</td><td>Syed Zeeshan Haider Jawadi</td><td><a href="/trans/ur.jawadi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ur.jawadi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ur.jawadi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="pk flag"></i>Urdu</td><td>محمد جوناگڑھی</td><td>Muhammad Junagarhi&nbsp;<a href="http://ur.wikipedia.org/wiki/مولانا_محمد_جوناگڑھی" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ur.junagarhi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ur.junagarhi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ur.junagarhi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="pk flag"></i>Urdu</td><td>محمد حسین نجفی</td><td>Muhammad Hussain Najafi &nbsp;<a href="http://en.wikipedia.org/wiki/Muhammad_Hussain_Najafi" title="Biography" class="bio"><sup>*</sup></a></td><td><a href="/trans/ur.najafi" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ur.najafi/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ur.najafi" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="cn flag"></i>Uyghur</td><td>محمد صالح</td><td>Muhammad Saleh</td><td><a href="/trans/ug.saleh" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/ug.saleh/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/ug.saleh" class="icon diff" title="Changelog"> </a></td></tr>
<tr><td><i class="uz flag"></i>Uzbek</td><td>Мухаммад Содик</td><td>Muhammad Sodik Muhammad Yusuf</td><td><a href="/trans/uz.sodik" title="Download" class="icon download" onclick="return download_action(this)"> </a> <a href="/#trans/uz.sodik/1:1" title="Browse" class="icon browse"> </a> <a href="/trans/log/uz.sodik" class="icon diff" title="Changelog"> </a></td></tr>
		</tbody>
	<tfoot></tfoot></table>
    """.trimIndent()
}